---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Check if role variables are defined
  fail: msg="distribution is undefined for the pkgrepo role"
  when: distribution is undefined

- name: Set up debian style repository
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  include_tasks: debian.yml

- name: Set up redhat style repository
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  include_tasks: redhat.yml
