---
# Copyright (c) 2019-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

services:
  analytics:
    host: "localhost"
    port: 9200
    proxy_type: "clientcert"

  cwf:
    host: "localhost"
    port: 9115
    echo_port: 10115
    proxy_type: "clientcert"
