---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- name: Install openvswitch and dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  include_tasks: debian.yml

- name: Load the ovs kernel module
  become: true
  script: reload_ovs_kmod.sh
  tags:
      - kernel_module_reload

- name: Start OVS
  service:
    name: openvswitch-switch
    state: started
    enabled: yes
    use: service
  become: true
