---
################################################################################
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
################################################################################

- name: Install OVS Dependencies for Red Hat
  yum:
    state: present
    name:
      - graphviz
      - bzip2
      - openssl
      - procps
      - python-six
      - yum-plugin-versionlock

- name: Install patched OVS v2.13.0 from Magma's pkgrepo
  yum:
     state: present
     name:
       - openvswitch-all
       
- name: Ensure OVS switch will not auto-upgrade
  shell: yum versionlock openvswitch-all
  args:
    warn: false

- name: Load the ovs kernel module
  # currently running userspace openvswitch -- disable until
  # kernel module supported
  become: true
  when: false
  script: reload_ovs_kmod.sh
  tags:
      - kernel_module_reload

- name: Start OVS
  service:
    name: openvswitch
    state: started
    enabled: yes
  become: true
